name: Build Linux Universal

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-cursor0 libxcb-xinerama0
        python -m pip install --upgrade pip
        pip install PyQt6 pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --name DailyReminder --icon=logo.png main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DailyReminder_Linux_Universal
        path: |
          dist/DailyReminder
          logo.png
